### ISSUE TITLE
sqlAlchemy Trino

### ISSUE THREAD

**Issue by diegorogo96** [cloudera/hue#2582] opened 2021-09-27 11:50 UTC
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
I haven't found anything related to this.

Describe the bug:
We are connecting Hue to Trino using sqlAlchemy so we can use an editor on Hue. This connection is working and most of the time the queries return the correct results, but some times (around a third of the times) instead of returning anything it simply returns this error: "Should be running if processing response"

![image](https://user-images.githubusercontent.com/48766802/134901200-92d23201-3cdb-46fa-9899-bae7d76e4242.png)

This is the error that is displayed on the logs:

[27/Sep/2021 13:39:25 +0200] sql_alchemy  ERROR    Query Error
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 99, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 318, in check_status
    if (self.options['url'].startswith('presto://') | self.options['url'].startswith('trino://')) and cursor and cursor.poll():
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/pyhive/presto.py", line 303, in poll
    self._process_response(response)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/pyhive/trino.py", line 113, in _process_response
    assert self._state == self._STATE_RUNNING, "Should be running if processing response"
AssertionError: Should be running if processing response

Even if Hue displays an error, the query finishes correctly on Trino.

Steps to reproduce it?

Launch any query to Trino using the Hue editor.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

We are using Hue version 4.10 from this Docker image: gethue/hue:20210908-140101
Trino version 361

Configuration on hue.ini:
    [[[trino]]]
      name = Trino
      interface=sqlalchemy
      options='{"url": "trino://xxx:8080/hive_local/default" , "has_impersonation": true}'

What do you think could be causing this error?
Thank you!

**Comment by sbbagal13** [comment] 2023-01-04 22:21
Hi Team , 
I too facing same issue ? do we have any workaround for this 
@diegorogo96 are you able to resolve it

**Comment by bjornalm** [comment] 2023-01-05 08:26
@Harshg999 Any thoughts?

**Comment by bjornalm** [comment] 2023-02-21 11:10
Looks like a duplicate of https://github.com/cloudera/hue/issues/3167

**Closed** 2023-02-21 11:09 UTC
