### ISSUE TITLE
Spnego authentication backend should return "Permission denied" for non existing user

### ISSUE THREAD

**Issue by fnerdwq** [cloudera/hue#269] opened 2015-12-07 09:35 UTC
Using the `desktop.auth.backend.SpnegoDjangoBackend` for authentication, the error returned when trying to login with a non-existing user (automatic creation of users is disabled) is a stacktrace:

```
AttributeError at /
'NoneType' object has no attribute 'get_groups'

Request Method: GET
Request URL: https://some.host.com:8888/
Django Version: 1.6.10
Exception Type: AttributeError
Exception Value:  'NoneType' object has no attribute 'get_groups'
Exception Location: /usr/share/hue-git/hue/desktop/core/src/desktop/auth/backend.py in rewrite_user, line 83
Python Executable: /usr/share/hue-git/hue/build/env/bin/python2.6
Python Version: 2.6.6
...
```

This should be a clean **Permission denied** or similar for the end user.

**Comment by spaztic1215** [comment] 2015-12-07 23:49
@fnerdwq what is your user_aug configuration set to?  Is it desktop.auth.backend.DefaultUserAugmentor ? Also, how did you disable creation of users, by setting create_users_on_login?

**Comment by fnerdwq** [comment] 2015-12-08 13:16
I'm using Hue 3.9 and not setting the `user_augmentor` explicitly therfore I suppose I'm using `desktop.auth.backend.DefaultUserAugmentor`.
And yes, `create_users_on_login` is disabled. Users allowed to login are synced from ldap explicitly.

**Comment by spaztic1215** [comment] 2015-12-08 22:23
@fnerdwq so Hue actually only uses the `create_users_on_login` configuration for LDAP (and OpenID and SAML, but they have separate configuration sections with their own `create_users_on_login` conf value). So the `SpnegoDjangoBackend` will actually attempt to create any new users on authentication (https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/auth/backend.py#L487-L499).

As for the error you are seeing, that is raised if for some reason Hue was unable to initialize an augmentor class for the given user:  https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/auth/backend.py#L75-L84

Can you check the logs and look for any messages that say ""Augmenting users with class:" or "Could not find user_augmentation_class"?  That would help point to the actual underlying issue.

**Comment by fnerdwq** [comment] 2015-12-09 08:17
Hi @spaztic1215 

so there is no way to explicitly block non-authorized users in the Spengo Backend? The only way is mapping them to the _default_ role w/o permissions?

The augmentor class seems to be loaded correctly
```
Augmenting users with class: <class 'desktop.auth.backend.DefaultUserAugmentor'>
```
So I don't find the errors you are suggesting.

The full stack trace
```
[09/Dec/2015 08:56:34 +0100] middleware   ERROR    Unexpected error when authenticating against KDC
Traceback (most recent call last):
  File "/usr/share/hue-test/hue/desktop/core/src/desktop/middleware.py", line 547, in process_request
    if request.user.is_authenticated():
  File "/usr/share/hue-test/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/usr/share/hue-test/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/utils/functional.py", line 298, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/share/hue-test/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/contrib/auth/middleware.py", line 18, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/share/hue-test/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/share/hue-test/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/contrib/auth/__init__.py", line 144, in get_user
    user = backend.get_user(user_id) or AnonymousUser()
  File "/usr/share/hue-test/hue/desktop/core/src/desktop/auth/backend.py", line 516, in get_user
    user = rewrite_user(user)
  File "/usr/share/hue-test/hue/desktop/core/src/desktop/auth/backend.py", line 82, in rewrite_user
    setattr(user, attr, getattr(augment, attr))
AttributeError: 'NoneType' object has no attribute 'get_groups'
```

**Comment by romainr** [comment] 2015-12-09 16:03
Isn't just user None as it does not exist so we should not try to rewrite it?

```
if user is not None:
  user = rewrite_user(user)
```

**Comment by spaztic1215** [comment] 2015-12-09 17:53
I can't reproduce the case where user is None b/c for Spnego backend, if the user has a valid Kerberos ticket then we always call this block to find or create the user if the user doesn't exist in Hue: https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/auth/backend.py#L487-L499

**Comment by fnerdwq** [comment] 2015-12-09 20:18
if I can provide more information, let me know...

**Comment by spaztic1215** [comment] 2015-12-09 20:38
@fnerdwq can you attempt to add the conditional that @romainr suggested, above this line: https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/auth/backend.py#L501

Let us know if that works.

**Comment by fnerdwq** [comment] 2015-12-10 07:25
It seems to work just fine (after getting around the browser caching :-)
So this seems to solve the issue.

Would be great to additionally have a `create_users_on_login=no` for authorization - to raise a "Permission denied" to the unauthorized user. But I suppose that's a feature request...

Thanks!

**Comment by spaztic1215** [comment] 2015-12-10 18:15
Fixed with https://github.com/cloudera/hue/commit/cd94b1b605bc95c139290652781cf2ca8802aa2e

**Closed by spaztic1215** 2015-12-10 18:15 UTC

**Comment by fnerdwq** [comment] 2016-02-19 08:01
Sorry, to reopen this, but I still observing the same stack for non-existing users...
